name: Debug JSON Issue

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  debug-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq (JSON Processor)
        run: sudo apt-get install -y jq

      - name: Download JSON File
        run: |
          echo "Downloading index.json..."
          curl -L -s -o index.json https://raw.githubusercontent.com/say274/SAT-Words/main/index.json?timestamp=$(date +%s)

          if [[ ! -s index.json ]]; then
            echo "❌ ERROR: index.json is empty or not downloaded!" >&2
            exit 5
          fi

          echo "✅ Successfully downloaded index.json. Here is what GitHub sees:"
          cat index.json  # Show what GitHub actually downloaded
          
